name: deploy frontend and storybook

on:
  push:
    branches: ['develop']

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build

      - name: Create 404.html for GitHub Pages
        run: |
          cp dist/index.html dist/404.html
          echo '
          <script>
            if (!location.pathname.startsWith("/storybook")) {
              location.href = "/";
            }
          </script>
          ' >> dist/404.html

      - name: Upload Frontend to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: .
          keep_files: true

      - name: Build Storybook
        run: npm run build-storybook

      - name: Update Storybook Base Path
        run: |
          echo "Updating Storybook base path for /storybook"
          sed -i 's|href="/|href="/storybook/|g' storybook-static/index.html
          sed -i 's|src="/|src="/storybook/|g' storybook-static/index.html

      - name: Upload Storybook to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          destination_dir: storybook
          keep_files: true
